workspace:
  base: /src
  path: ${DRONE_REPO_NAME}

pipeline:
  test:
    image: golang:1.13
    commands:
      - go test ./...
    when:
      event: pull_request

  build:
    image: golang:1.13
    environment:
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go build
    when:
      event: pull_request

  publish:
    image: plugins/docker
    settings:
      repo: nkristianto/drone_test
      tags: [ "${DRONE_COMMIT_SHA:0:4}" ]
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event: [ push ]
      branch: master
