workspace:
  base: /src
  path: ${DRONE_REPO_NAME}

pipeline:
  test:
    image: golang:1.13
    volumes:
      - name: deps
        path: /go
    commands:
      - go test ./...

  build:
    image: golang:1.13
    volumes:
      - name: deps
        path: /go
    environment:
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go build
